### ISSUE TITLE
Smart Menu Functionality

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Syr-Digital-Launch#4]
Intuitive Dropdown menu items - Are the menu items intuitive at this time?  If not, this customer is 3day FOD and the menu is suggesting to upgrade to 3day FOD.

![727d9a82-9129-4d76-a4a6-6dbb17bf03f7](https://user-images.githubusercontent.com/25616598/45360758-8c69bc00-b59e-11e8-9421-8ea893ab7cbe.png)

**Comment by mkoza178** [comment]
This is, frankly, not included in the dynamic menu work. 
This one would be a bit challenging because it's based off household level/service type and that can change by site. So my question would be: is it worth having it as a menu item on the dashboard? I believe you have direct marketing campaigns, those would still work.

**Comment by mkoza178** [comment]
We will remove 'Upgrade to 3-Day home delivery' from the menu and Share Your Subscription.
